# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: BrowserStackResults@0
- task: NodeTool@0
  inputs:
    versionSpec: '6.15.1'
    checkLatest: false
- script: node -v
- script: npm install
- script: npm uninstall fibers
- script: npm install fibers
- script: ls ./node_modules/.bin | grep wdio
- script: ./node_modules/.bin/wdio -v
- script: npx wdio -v
- script: npm run single
  displayName: 'Run a one-line script'
- task: BrowserStackResults@0


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
